use_frameworks!

platform :ios, '15.0'

install! 'cocoapods', :disable_input_output_paths => true

target 'TQIExtractDIO_Example' do
  pod 'TQIExtractDIO', :path => '../'

  target 'TQIExtractDIO_Tests' do
    inherit! :search_paths

    
  end
end
